'use client'

import { useMemo, useState } from 'react'
import { ArrowRight, ChevronDown, CircleDot, Heart, Menu, Search, SlidersHorizontal, Sparkles, X } from 'lucide-react'

const stages = [
  { id: 'birth', label: 'Birth', period: 'Day 0', icon: '✦', accent: '#d88767', description: 'A new life begins. Puppies arrive with their eyes and ears closed, guided by scent, touch, and the warmth of their mother.', tags: ['Newborn', 'Dependent', 'Scent-led'], body: 'The first hours are about warmth, nursing, and quiet bonding. Healthy puppies should be observed closely and checked by a veterinary professional.' },
  { id: 'neonatal', label: 'Neonatal', period: '0–2 weeks', icon: '◒', accent: '#bf8f6e', description: 'The smallest world: sleep, suckle, grow. Senses are still unfolding while the body changes almost daily.', tags: ['Sleep', 'Nursing', 'Rapid growth'], body: 'Puppies spend most of their time sleeping and feeding. Gentle, safe handling helps them begin to experience the world, but they remain fully dependent.' },
  { id: 'puppy', label: 'Puppy', period: '3–16 weeks', icon: '◌', accent: '#6f9c85', description: 'Eyes open. Feet find the floor. The world becomes a place to investigate, play in, and learn from.', tags: ['Socialization', 'Play', 'Learning'], body: 'This is a sensitive learning window. Positive introductions to people, surfaces, sounds, and calm routines build confidence without overwhelming the puppy.' },
  { id: 'adolescent', label: 'Adolescent', period: '4–18 months', icon: '⌁', accent: '#d5a34e', description: 'A teenager in a dog’s body: growing independence, changing hormones, and a brain still learning to pause.', tags: ['Curiosity', 'Energy', 'Boundaries'], body: 'Growth and maturity do not arrive together. Keep training reward-based, provide appropriate exercise, and expect some backsliding while self-control develops.' },
  { id: 'adult', label: 'Adult', period: '1–7+ years', icon: '○', accent: '#547b69', description: 'Body and personality settle into a rhythm. Adult life is about maintaining health, connection, and curiosity.', tags: ['Maintenance', 'Routine', 'Vitality'], body: 'Maturity varies widely by size and breed. Balanced nutrition, body-condition monitoring, daily enrichment, and preventive care support a long, active life.' },
  { id: 'senior', label: 'Senior', period: '7+ years', icon: '◓', accent: '#8c779d', description: 'The pace may soften, but the need for comfort, engagement, and companionship remains wonderfully constant.', tags: ['Comfort', 'Adaptation', 'Wisdom'], body: 'Age-related changes can be subtle. Regular veterinary visits and small adjustments to movement, food, home layout, and routines can make a big difference.' },
]

const breeds = [
  { name: 'Chihuahua', size: 'Toy', life: '14–17 yrs', energy: 3, groom: 1, maturity: '8–10 mo', image: '/images/chihuahua.png', blurb: 'Alert, confident, and tiny in stature with a surprisingly big personality.' },
  { name: 'Labrador Retriever', size: 'Large', life: '10–12 yrs', energy: 5, groom: 2, maturity: '18–24 mo', image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80', blurb: 'Outgoing, eager to learn, and happiest when included in family life.' },
  { name: 'Border Collie', size: 'Medium', life: '12–15 yrs', energy: 5, groom: 3, maturity: '18–24 mo', image: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=600&q=80', blurb: 'Bright, athletic, and deeply responsive to thoughtful work and play.' },
  { name: 'Great Dane', size: 'Giant', life: '7–10 yrs', energy: 3, groom: 1, maturity: '24–36 mo', image: '/images/great-dane.png', blurb: 'Gentle and affectionate, with a long adolescent growth period.' },
]

const matrix = [
  ['Body', 'Fast growth; soft joints', 'Awkward, changing', 'Strong, stable', 'Muscle and mobility support'],
  ['Brain', 'Absorbs safe experiences', 'Impulse control grows', 'Learns throughout life', 'Gentle enrichment matters'],
  ['Nutrition', 'Puppy-formulated fuel', 'Watch body condition', 'Balanced portions', 'Adjust for activity'],
  ['Exercise', 'Short, gentle play', 'Structured outlets', 'Daily variety', 'Low-impact consistency'],
  ['Care', 'Vaccines & socialization', 'Training & safety', 'Preventive checks', 'More frequent monitoring'],
]

export default function Page() {
  const [activeStage, setActiveStage] = useState('puppy')
  const [query, setQuery] = useState('')
  const [size, setSize] = useState('All sizes')
  const [compare, setCompare] = useState(['Chihuahua', 'Great Dane'])
  const [menuOpen, setMenuOpen] = useState(false)
  const stage = stages.find((item) => item.id === activeStage) ?? stages[2]
  const filtered = useMemo(() => breeds.filter((breed) => breed.name.toLowerCase().includes(query.toLowerCase()) && (size === 'All sizes' || breed.size === size)), [query, size])

  const toggleCompare = (name: string) => setCompare((current) => current.includes(name) ? current.filter((item) => item !== name) : current.length < 4 ? [...current, name] : current)

  return (
    <main className="site-shell">
      <header className="topbar">
        <a className="brand" href="#top"><span className="brand-mark">✦</span><span>canis / <b>life study</b></span></a>
        <nav className={menuOpen ? 'nav-links is-open' : 'nav-links'} aria-label="Primary navigation">
          <a href="#journey" onClick={() => setMenuOpen(false)}>Life stages</a><a href="#first-year" onClick={() => setMenuOpen(false)}>First year</a><a href="#breeds" onClick={() => setMenuOpen(false)}>Breeds</a><a href="#compare" onClick={() => setMenuOpen(false)}>Compare</a><a href="#aging" onClick={() => setMenuOpen(false)}>Aging</a>
        </nav>
        <button className="menu-button" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X size={20}/> : <Menu size={20}/>}</button>
      </header>

      <section className="hero" id="top">
        <div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot"/> A field guide to growing up</p><h1>The life<br/><em>of a small beast</em></h1><p className="hero-text">From the first breath to the final years — understand how dogs grow, mature, age, and experience life differently across breeds.</p><a className="primary-button" href="#journey">Explore the journey <ArrowRight size={17}/></a><div className="hero-stats"><div><strong>7</strong><span>life chapters</span></div><div><strong>7–17</strong><span>typical years</span></div><div><strong>∞</strong><span>individual paths</span></div></div></div>
        <div className="hero-visual"><div className="sun-orbit"/><div className="hero-image-wrap"><img src="https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1000&q=85" alt="Border collie looking toward the camera"/></div><div className="image-note"><span>01 / 09</span><b>every beginning<br/>holds a whole world</b></div><div className="floating-chip chip-top">✦ <span>curiosity</span></div><div className="floating-chip chip-bottom"><Heart size={13} fill="currentColor"/> <span>connection</span></div></div>
      </section>

      <section className="journey-section section-pad" id="journey"><div className="section-intro"><p className="eyebrow">01 — The journey</p><h2>One broad arc.<br/><em>Many different tempos.</em></h2><p>Every dog travels through the same broad chapters, but age boundaries are not hard lines. Size, breed, genetics, nutrition, health, and the individual all shape the pace.</p></div><div className="stage-layout"><div className="stage-list" role="tablist" aria-label="Dog life stages">{stages.map((item, index) => <button key={item.id} className={activeStage === item.id ? 'stage-item active' : 'stage-item'} onClick={() => setActiveStage(item.id)} role="tab" aria-selected={activeStage === item.id}><span className="stage-number">0{index + 1}</span><span className="stage-icon" style={{color:item.accent}}>{item.icon}</span><span><b>{item.label}</b><small>{item.period}</small></span><ArrowRight className="stage-arrow" size={16}/></button>)}</div><article className="stage-detail" style={{'--stage-accent': stage.accent} as React.CSSProperties}><div className="detail-kicker">{stage.period} <span>·</span> {stage.label}</div><h3>{stage.description}</h3><div className="tag-row">{stage.tags.map(tag => <span key={tag}>{tag}</span>)}</div><p>{stage.body}</p><div className="detail-grid"><div><small>What changes</small><b>{stage.label === 'Puppy' ? 'Senses, movement, attachment' : 'Body, behavior & daily needs'}</b></div><div><small>Owner focus</small><b>{stage.label === 'Senior' ? 'Comfort & early observation' : 'Safety, patience & routine'}</b></div></div></article></div></section>

      <section className="cream-band" id="first-year"><div className="section-pad first-year"><div className="section-intro compact"><p className="eyebrow">02 — The first year</p><h2>Small weeks.<br/><em>Huge changes.</em></h2><p>Development is fast in the first year, but not perfectly scheduled. Think in windows of opportunity, not deadlines.</p></div><div className="growth-card"><div className="growth-head"><span>development map</span><b>week 1 <i>→</i> month 12</b></div><div className="growth-line">{['wk 1','wk 2','wk 3','wk 4','mo 2','mo 3','mo 4','mo 5','mo 6','mo 7','mo 8','mo 9','mo 10','mo 11','mo 12'].map((month, i) => <div key={month} className={i === 4 || i === 7 || i === 11 ? 'growth-point highlight' : 'growth-point'}><span>{month}</span><i/></div>)}</div><div className="growth-caption"><b>early socialization</b><span>brain & body keep catching up</span><b>adult patterns emerge</b></div><div className="milestone"><Sparkles size={18}/><div><small>right now</small><strong>Explore gently, reward generously.</strong><p>Positive experiences with people, places, handling, and calm routines create a foundation — without rushing the puppy past their comfort zone.</p></div></div></div></div></section>

      <section className="section-pad" id="breeds"><div className="section-heading-row"><div><p className="eyebrow">03 — Breed explorer</p><h2>Different bodies.<br/><em>Different clocks.</em></h2></div><p>Compare common breeds and see how size, energy, grooming, and maturity can change the everyday experience of a dog’s life.</p></div><div className="explorer-tools"><div className="search-wrap"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a breed" aria-label="Search a breed"/></div><select value={size} onChange={e=>setSize(e.target.value)} aria-label="Filter by size"><option>All sizes</option>{['Toy','Small','Medium','Large','Giant'].map(item=><option key={item}>{item}</option>)}</select><button className="filter-button"><SlidersHorizontal size={16}/> Filters</button></div><div className="breed-grid">{filtered.map(breed => <article className="breed-card" key={breed.name}><div className="breed-image"><img src={breed.image} alt={breed.name}/><span>{breed.size}</span></div><div className="breed-content"><div className="breed-title"><h3>{breed.name}</h3><button className={compare.includes(breed.name) ? 'compare-toggle selected' : 'compare-toggle'} onClick={() => toggleCompare(breed.name)} aria-label={`Compare ${breed.name}`}>{compare.includes(breed.name) ? '✓' : '+'}</button></div><p>{breed.blurb}</p><div className="breed-meta"><span><small>lifespan</small><b>{breed.life}</b></span><span><small>matures</small><b>{breed.maturity}</b></span></div><div className="meter-row"><span>energy</span><div className="meters">{[1,2,3,4,5].map(i=><i key={i} className={i<=breed.energy?'on':''}/>)}</div><span className="meter-label">{breed.energy > 3 ? 'high' : 'moderate'}</span></div></div></article>)}</div></section>

      <section className="dark-band" id="compare"><div className="section-pad compare-section"><div className="section-heading-row light"><div><p className="eyebrow">04 — Side by side</p><h2>Same journey.<br/><em>Different experience.</em></h2></div><p>Select up to four breeds above to make a quick, visual comparison.</p></div><div className="comparison-table"><div className="comparison-row table-header"><div>attribute</div>{compare.map(name=><div key={name}>{name}</div>)}</div>{[['Size','Toy','Giant'],['Lifespan','14–17 yrs','7–10 yrs'],['Maturity','8–10 mo','24–36 mo'],['Energy','Moderate','Moderate'],['Grooming','Low','Low']].map(row=><div className="comparison-row" key={row[0]}><div>{row[0]}</div>{compare.map(name=><div key={name}>{name === 'Chihuahua' ? row[1] : name === 'Great Dane' ? row[2] : row[0] === 'Size' ? 'Medium' : row[0] === 'Lifespan' ? '10–15 yrs' : 'Varies'}</div>)}</div>)}</div><p className="data-note">Population-level estimates shown for education, not guarantees for an individual dog.</p></div></section>

      <section className="aging-section section-pad" id="aging"><div className="aging-copy"><p className="eyebrow">05 — Aging, re-framed</p><h2>There is no<br/><em>“one dog year.”</em></h2><p>The familiar 1:7 rule is easy to remember, but biology is more nuanced. Dogs age quickly during early life, then the pace shifts — with size and breed influencing the curve.</p><div className="quote-card"><CircleDot size={18}/><p>“Age is not simply a number. It is a pattern of change, shaped by the life lived.”</p></div></div><div className="age-chart"><div className="chart-labels"><span>human-age<br/>equivalent</span><b>80</b><b>40</b><b>20</b><b>0</b></div><div className="chart-visual"><div className="grid-line"/><div className="grid-line"/><div className="grid-line"/><svg viewBox="0 0 500 280" preserveAspectRatio="none" role="img" aria-label="Illustrative dog aging curve"><path d="M5 265 C 30 110, 55 52, 120 30 S 270 10, 495 2" fill="none" stroke="#d98768" strokeWidth="4"/><path d="M5 265 L495 2" fill="none" stroke="#c7bdb0" strokeWidth="1" strokeDasharray="5 8"/></svg><div className="chart-x"><span>puppy</span><span>adult</span><span>senior</span></div></div><div className="chart-legend"><span><i className="legend-dot coral"/>Illustrative aging curve</span><span><i className="legend-dot gray"/>1:7 myth</span></div></div></section>

      <section className="matrix-section section-pad"><div className="section-heading-row"><div><p className="eyebrow">06 — What changes?</p><h2>Read the signals.<br/><em>Meet the moment.</em></h2></div><p>A quick-reference view of how the same needs evolve from puppyhood to the senior years.</p></div><div className="matrix"><div className="matrix-row matrix-head"><div>life area</div><div>puppy</div><div>adolescent</div><div>adult</div><div>senior</div></div>{matrix.map(row=><div className="matrix-row" key={row[0]}>{row.map((cell,i)=><div key={i} className={i===0?'row-label':''}>{cell}</div>)}</div>)}</div></section>

      <section className="end-band"><div className="section-pad end-content"><div><p className="eyebrow">07 — Golden years & goodbye</p><h2>A softer pace.<br/><em>A lasting bond.</em></h2></div><div className="end-copy"><p>Senior dogs may need more rest, more monitoring, and more thoughtful adaptations. Changes in mobility, appetite, senses, or behavior deserve a conversation with a veterinarian.</p><p>At the end of life, comfort and dignity come first. Quality-of-life support, palliative care, and compassionate veterinary guidance can help families make informed decisions and make space for grief.</p><a href="#top" className="text-link">Back to the beginning <ArrowRight size={15}/></a></div></div></section>

      <footer className="footer section-pad"><div className="brand"><span className="brand-mark">✦</span><span>canis / <b>life study</b></span></div><div className="footer-note"><span>Educational guide · 2026</span><span>Patterns vary. Every dog is an individual.</span></div><div className="sources"><b>Sources</b><span>American Kennel Club · AAHA · AVMA · Merck Veterinary Manual</span></div></footer>
    </main>
  )
}
